version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

go_image: &go_image
  resource_class: small
  docker:
    - image: cimg/go:1.23

jobs:
  security-scans:
    <<: *go_image
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto
          iac-scan: disabled

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: team-unify-alerts
          filters:
            branches:
              ignore:
                - main
      - security-scans:
          name: Security Scans
          context: analysis_unify
